"$schema" = 'https://starship.rs/config-schema.json'

[git_branch]
    symbol = ' '

[character]
    success_symbol = '[](bold green) '
    error_symbol = '[](bold red) '
    vimcmd_symbol = '[](bold green) '
